# Generated by Django 5.2.10 on 2026-01-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='difficulty',
            field=models.CharField(default='normal', max_length=20, verbose_name='難易度'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='gender',
            field=models.CharField(default='female', max_length=20, verbose_name='面接官性別'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='conversation_log',
            field=models.JSONField(default=list, verbose_name='会話履歴'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='feedback_text',
            field=models.JSONField(default=dict, verbose_name='AIフィードバック'),
        ),
    ]
